{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "b70d404c",
   "metadata": {},
   "source": [
    "# Group 1 Throw-In Project"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eb8a7d58",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Collecting tqdm\n",
      "  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)\n",
      "Requirement already satisfied: colorama in c:\\users\\earni\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\\localcache\\local-packages\\python313\\site-packages (from tqdm) (0.4.6)\n",
      "Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)\n",
      "Installing collected packages: tqdm\n",
      "Successfully installed tqdm-4.67.1\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  WARNING: The script tqdm.exe is installed in 'C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\Scripts' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\n"
     ]
    }
   ],
   "source": [
    "# %pip install tqdm\n",
    "# %pip install statsbombpy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "57e0ce99",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from statsbombpy import sb\n",
    "\n",
    "from typing import Optional, Iterable\n",
    "from statsbombpy import sb\n",
    "from tqdm.auto import tqdm"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "972fcebc",
   "metadata": {},
   "source": [
    "### Import Womans Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "9807cb4e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "WomenSL = sb.matches(competition_id=37, season_id=90) \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "8f538f4e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Fetching events:   0%|          | 0/131 [00:00<?, ?it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:   1%|          | 1/131 [00:00<00:53,  2.41it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:   2%|▏         | 2/131 [00:00<01:02,  2.06it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:   2%|▏         | 3/131 [00:01<00:57,  2.23it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:   3%|▎         | 4/131 [00:01<00:52,  2.40it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:   4%|▍         | 5/131 [00:02<00:50,  2.47it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:   5%|▍         | 6/131 [00:02<00:50,  2.50it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:   5%|▌         | 7/131 [00:02<00:50,  2.46it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:   6%|▌         | 8/131 [00:03<00:48,  2.55it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:   7%|▋         | 9/131 [00:03<00:47,  2.56it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:   8%|▊         | 10/131 [00:03<00:44,  2.70it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:   8%|▊         | 11/131 [00:04<00:45,  2.64it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:   9%|▉         | 12/131 [00:04<00:42,  2.80it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  10%|▉         | 13/131 [00:05<00:42,  2.80it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  11%|█         | 14/131 [00:05<00:48,  2.39it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  11%|█▏        | 15/131 [00:06<00:47,  2.44it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  12%|█▏        | 16/131 [00:06<00:49,  2.33it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  13%|█▎        | 17/131 [00:06<00:48,  2.33it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  14%|█▎        | 18/131 [00:07<00:50,  2.24it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  15%|█▍        | 19/131 [00:07<00:47,  2.35it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  15%|█▌        | 20/131 [00:08<00:45,  2.44it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  16%|█▌        | 21/131 [00:08<00:44,  2.49it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  17%|█▋        | 22/131 [00:08<00:46,  2.36it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  18%|█▊        | 23/131 [00:09<00:47,  2.30it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  18%|█▊        | 24/131 [00:09<00:44,  2.38it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  19%|█▉        | 25/131 [00:10<00:46,  2.27it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  20%|█▉        | 26/131 [00:10<00:47,  2.22it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  21%|██        | 27/131 [00:11<00:50,  2.04it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  21%|██▏       | 28/131 [00:11<00:48,  2.12it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  22%|██▏       | 29/131 [00:12<00:50,  2.00it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  23%|██▎       | 30/131 [00:12<00:45,  2.20it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  24%|██▎       | 31/131 [00:13<00:44,  2.26it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  24%|██▍       | 32/131 [00:13<00:43,  2.28it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  25%|██▌       | 33/131 [00:13<00:42,  2.31it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  26%|██▌       | 34/131 [00:14<00:40,  2.42it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  27%|██▋       | 35/131 [00:14<00:42,  2.28it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  27%|██▋       | 36/131 [00:15<00:44,  2.14it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  28%|██▊       | 37/131 [00:15<00:41,  2.26it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  29%|██▉       | 38/131 [00:16<00:41,  2.26it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  30%|██▉       | 39/131 [00:16<00:49,  1.87it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  31%|███       | 40/131 [00:17<00:48,  1.89it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  31%|███▏      | 41/131 [00:18<00:47,  1.89it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  32%|███▏      | 42/131 [00:18<00:42,  2.10it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  33%|███▎      | 43/131 [00:18<00:42,  2.07it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  34%|███▎      | 44/131 [00:19<00:41,  2.09it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  34%|███▍      | 45/131 [00:19<00:40,  2.14it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  35%|███▌      | 46/131 [00:20<00:36,  2.30it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  36%|███▌      | 47/131 [00:20<00:37,  2.24it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  37%|███▋      | 48/131 [00:21<00:36,  2.27it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  37%|███▋      | 49/131 [00:21<00:34,  2.40it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  38%|███▊      | 50/131 [00:21<00:33,  2.38it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  39%|███▉      | 51/131 [00:22<00:31,  2.53it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  40%|███▉      | 52/131 [00:22<00:38,  2.06it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  40%|████      | 53/131 [00:23<00:34,  2.23it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  41%|████      | 54/131 [00:23<00:35,  2.20it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  42%|████▏     | 55/131 [00:24<00:35,  2.15it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  43%|████▎     | 56/131 [00:24<00:39,  1.89it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  44%|████▎     | 57/131 [00:25<00:41,  1.79it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  44%|████▍     | 58/131 [00:25<00:36,  2.00it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  45%|████▌     | 59/131 [00:26<00:33,  2.16it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  46%|████▌     | 60/131 [00:26<00:30,  2.31it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  47%|████▋     | 61/131 [00:27<00:32,  2.16it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  47%|████▋     | 62/131 [00:27<00:32,  2.12it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  48%|████▊     | 63/131 [00:28<00:31,  2.17it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  49%|████▉     | 64/131 [00:28<00:35,  1.86it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  50%|████▉     | 65/131 [00:29<00:32,  2.00it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  50%|█████     | 66/131 [00:29<00:30,  2.14it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  51%|█████     | 67/131 [00:30<00:29,  2.18it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  52%|█████▏    | 68/131 [00:30<00:28,  2.21it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  53%|█████▎    | 69/131 [00:30<00:28,  2.20it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  53%|█████▎    | 70/131 [00:31<00:29,  2.04it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  54%|█████▍    | 71/131 [00:31<00:29,  2.06it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  55%|█████▍    | 72/131 [00:32<00:26,  2.24it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  56%|█████▌    | 73/131 [00:32<00:23,  2.43it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  56%|█████▋    | 74/131 [00:33<00:23,  2.41it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  57%|█████▋    | 75/131 [00:33<00:23,  2.42it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  58%|█████▊    | 76/131 [00:33<00:21,  2.52it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  59%|█████▉    | 77/131 [00:34<00:24,  2.19it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  60%|█████▉    | 78/131 [00:35<00:33,  1.57it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  60%|██████    | 79/131 [00:35<00:29,  1.74it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  61%|██████    | 80/131 [00:36<00:26,  1.95it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  62%|██████▏   | 81/131 [00:36<00:24,  2.06it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  63%|██████▎   | 82/131 [00:37<00:25,  1.94it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  63%|██████▎   | 83/131 [00:38<00:28,  1.69it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  64%|██████▍   | 84/131 [00:38<00:29,  1.58it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  65%|██████▍   | 85/131 [00:39<00:27,  1.65it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  66%|██████▌   | 86/131 [00:39<00:25,  1.78it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  66%|██████▋   | 87/131 [00:40<00:22,  1.97it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  67%|██████▋   | 88/131 [00:40<00:20,  2.14it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  68%|██████▊   | 89/131 [00:40<00:19,  2.20it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  69%|██████▊   | 90/131 [00:41<00:18,  2.25it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  69%|██████▉   | 91/131 [00:41<00:17,  2.32it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  70%|███████   | 92/131 [00:42<00:17,  2.28it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  71%|███████   | 93/131 [00:42<00:17,  2.23it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  72%|███████▏  | 94/131 [00:43<00:20,  1.82it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  73%|███████▎  | 95/131 [00:43<00:17,  2.02it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  73%|███████▎  | 96/131 [00:44<00:16,  2.17it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  74%|███████▍  | 97/131 [00:44<00:14,  2.34it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  75%|███████▍  | 98/131 [00:44<00:13,  2.45it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  76%|███████▌  | 99/131 [00:45<00:16,  1.90it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  76%|███████▋  | 100/131 [00:46<00:15,  1.95it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  77%|███████▋  | 101/131 [00:46<00:16,  1.86it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  78%|███████▊  | 102/131 [00:47<00:15,  1.89it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  79%|███████▊  | 103/131 [00:47<00:14,  1.93it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  79%|███████▉  | 104/131 [00:48<00:12,  2.08it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  80%|████████  | 105/131 [00:48<00:11,  2.18it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  81%|████████  | 106/131 [00:49<00:11,  2.16it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  82%|████████▏ | 107/131 [00:49<00:10,  2.19it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  82%|████████▏ | 108/131 [00:50<00:10,  2.18it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  83%|████████▎ | 109/131 [00:50<00:11,  1.99it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  84%|████████▍ | 110/131 [00:51<00:15,  1.34it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  85%|████████▍ | 111/131 [00:52<00:13,  1.52it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  85%|████████▌ | 112/131 [00:52<00:11,  1.68it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  86%|████████▋ | 113/131 [00:53<00:09,  1.84it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  87%|████████▋ | 114/131 [00:53<00:08,  1.94it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  88%|████████▊ | 115/131 [00:54<00:07,  2.17it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  89%|████████▊ | 116/131 [00:54<00:06,  2.15it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  89%|████████▉ | 117/131 [00:54<00:06,  2.30it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  90%|█████████ | 118/131 [00:55<00:05,  2.23it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  91%|█████████ | 119/131 [00:55<00:05,  2.17it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  92%|█████████▏| 120/131 [00:56<00:05,  2.15it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  92%|█████████▏| 121/131 [00:56<00:04,  2.19it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  93%|█████████▎| 122/131 [00:57<00:03,  2.34it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  94%|█████████▍| 123/131 [00:57<00:03,  2.41it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  95%|█████████▍| 124/131 [00:57<00:02,  2.47it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  95%|█████████▌| 125/131 [00:58<00:02,  2.42it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  96%|█████████▌| 126/131 [00:58<00:02,  2.38it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  97%|█████████▋| 127/131 [00:59<00:01,  2.29it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  98%|█████████▊| 128/131 [00:59<00:01,  2.16it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  98%|█████████▊| 129/131 [01:00<00:00,  2.22it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events:  99%|█████████▉| 130/131 [01:00<00:00,  2.32it/s]C:\\Users\\Earni\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\statsbombpy\\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only\n",
      "  warnings.warn(\n",
      "Fetching events: 100%|██████████| 131/131 [01:01<00:00,  2.13it/s]\n"
     ]
    }
   ],
   "source": [
    "def build_events_dataset(\n",
    "    matches_df: pd.DataFrame,\n",
    "    match_id_col: str = \"match_id\",\n",
    "    save_csv: Optional[str] = None,\n",
    "    keep_columns: Optional[Iterable[str]] = None,\n",
    "    add_meta: bool = True,\n",
    "    ) -> pd.DataFrame:\n",
    "\n",
    "# Fetch events for all match_ids in `matches_df`, concatenate into one DataFrame,\n",
    "# and (optionally) merge key match metadata columns.\n",
    "\n",
    "# Parameters\n",
    "# ----------\n",
    "# matches_df : DataFrame containing at least `match_id`\n",
    "# match_id_col : name of the match id column\n",
    "# save_parquet : path to save a Parquet file (recommended)\n",
    "# save_csv : path to save a CSV file\n",
    "# keep_columns : iterable of event columns to keep (None = keep all)\n",
    "# add_meta : merge match metadata columns (season, teams, date, week, competition)\n",
    "\n",
    "# Returns\n",
    "# -------\n",
    "# DataFrame of all events with `match_id` and optional metadata.\n",
    "\n",
    "    if match_id_col not in matches_df.columns:\n",
    "        raise KeyError(f\"`{match_id_col}` not in matches_df columns\")\n",
    "\n",
    "\n",
    "    meta_cols = [\n",
    "    match_id_col,\n",
    "    \"season\", \"season_id\", \"season_name\",\n",
    "    \"competition\", \"competition_id\", \"competition_name\",\n",
    "    \"match_date\", \"match_week\",\n",
    "    \"home_team\", \"away_team\"\n",
    "    ]\n",
    "    meta = matches_df[[c for c in meta_cols if c in matches_df.columns]].drop_duplicates()\n",
    "\n",
    "    all_frames = []\n",
    "    failures = []\n",
    "\n",
    "    mids = pd.unique(matches_df[match_id_col].astype(\"int64\"))\n",
    "    for mid in tqdm(mids, desc=\"Fetching events\"):\n",
    "        try:\n",
    "            ev = sb.events(match_id=int(mid))\n",
    "            ev[match_id_col] = int(mid)\n",
    "            all_frames.append(ev)\n",
    "        except Exception as e:\n",
    "            failures.append((int(mid), str(e)))\n",
    "\n",
    "    if not all_frames:\n",
    "        raise RuntimeError(\"No events were loaded. Check your match_ids or environment.\")\n",
    "\n",
    "    events = pd.concat(all_frames, ignore_index=True)\n",
    "\n",
    "\n",
    "    if keep_columns is not None:\n",
    "        keep = list(set(keep_columns) | {match_id_col})\n",
    "        events = events[[c for c in keep if c in events.columns]]\n",
    "\n",
    "\n",
    "    if add_meta and not meta.empty:\n",
    "        events = events.merge(meta, on=match_id_col, how=\"left\")\n",
    "\n",
    "\n",
    "    if save_csv:\n",
    "        events.to_csv(save_csv, index=False)\n",
    "        print(f\"Saved events: {len(events):,} rows → {save_csv}\")\n",
    "\n",
    "    if failures:\n",
    "        print(f\"\\n Skipped {len(failures)} matches due to errors (showing first 5):\")\n",
    "    for mid, msg in failures[:5]:\n",
    "        print(f\" match_id={mid}: {msg}\")\n",
    "\n",
    "    return events\n",
    "\n",
    "\n",
    "\n",
    "events_df = build_events_dataset(\n",
    "WomenSL,\n",
    "keep_columns=None,\n",
    "add_meta=True\n",
    ")\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "42fe21f8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(443304, 122)\n",
      "       match_id     season                   home_team  \\\n",
      "0       3775648  2020/2021                 Aston Villa   \n",
      "3811    3775609  2020/2021                 Arsenal WFC   \n",
      "7392    3775633  2020/2021                 Aston Villa   \n",
      "10742   3775570  2020/2021  Brighton & Hove Albion WFC   \n",
      "14444   3775581  2020/2021                 Chelsea FCW   \n",
      "\n",
      "                     away_team  \n",
      "0                  Arsenal WFC  \n",
      "3811       West Ham United LFC  \n",
      "7392   Tottenham Hotspur Women  \n",
      "10742              Everton LFC  \n",
      "14444              Aston Villa  \n"
     ]
    }
   ],
   "source": [
    "print(events_df.shape)\n",
    "print(events_df[[\"match_id\", \"season\", \"home_team\", \"away_team\"]].drop_duplicates().head())"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
